/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "KSA/KSA_4bit.v:4.1-93.10" *)
module kogge_stone_adder_4bit(a, b, cin, sum, cout);
  (* src = "KSA/KSA_4bit.v:5.18-5.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "KSA/KSA_4bit.v:6.18-6.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "KSA/KSA_4bit.v:7.18-7.21" *)
  input cin;
  wire cin;
  (* src = "KSA/KSA_4bit.v:8.18-8.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "KSA/KSA_4bit.v:9.18-9.22" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "KSA/KSA_4bit.v:65.16-65.18" *)
  wire [3:0] g2;
  (* src = "KSA/KSA_4bit.v:38.20-38.22" *)
  wire [3:0] p1;
  assign _00_ = ~(a[2] & b[2]);
  assign _01_ = ~(a[1] & b[1]);
  assign _10_ = ~(_08_ & _09_);
  assign _11_ = ~(_00_ & _10_);
  assign _12_ = ~(a[3] & b[3]);
  assign _13_ = a[3] ^ b[3];
  assign _14_ = ~(_11_ & _13_);
  assign sum[3] = _11_ ^ _13_;
  assign cout = ~(_12_ & _14_);
  assign sum[0] = cin ^ _03_;
  assign sum[1] = _05_ ^ _06_;
  assign sum[2] = _08_ ^ _09_;
  assign _02_ = ~(a[0] & b[0]);
  assign _03_ = a[0] ^ b[0];
  assign _04_ = ~(cin & _03_);
  assign _05_ = ~(_02_ & _04_);
  assign _06_ = a[1] ^ b[1];
  assign _07_ = ~(_05_ & _06_);
  assign _08_ = ~(_01_ & _07_);
  assign _09_ = a[2] ^ b[2];
  assign g2[3] = cout;
  assign p1[1] = 1'hx;
endmodule
