/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "CLA/CLA_4bit.v:1.1-141.10" *)
module CLA_4bit_gate_level(a, b, cin, sum, cout);
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "CLA/CLA_4bit.v:4.18-4.21" *)
  input cin;
  wire cin;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "CLA/CLA_4bit.v:6.18-6.22" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  wire _15_;
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  wire _16_;
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  wire _17_;
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  wire _18_;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  wire _19_;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  wire _20_;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  wire _21_;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  wire _22_;
  (* src = "CLA/CLA_4bit.v:4.18-4.21" *)
  wire _23_;
  (* src = "CLA/CLA_4bit.v:6.18-6.22" *)
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  wire _32_;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  wire _33_;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  wire _34_;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  wire _35_;
  (* src = "CLA/CLA_4bit.v:14.22-14.24" *)
  wire c4;
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_15_),
    .B(_19_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__maj3_1 _37_ (
    .A(_23_),
    .B(_15_),
    .C(_19_),
    .X(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(_23_),
    .B(_25_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__maj3_1 _39_ (
    .A(_18_),
    .B(_22_),
    .C(_30_),
    .X(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(_16_),
    .B(_20_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(_16_),
    .B(_20_),
    .C(_26_),
    .X(_28_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_17_),
    .B(_21_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(_17_),
    .B(_21_),
    .C(_28_),
    .X(_30_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_18_),
    .B(_22_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_30_),
    .B(_31_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_28_),
    .B(_29_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_26_),
    .B(_27_),
    .Y(_33_)
  );
  assign c4 = cout;
  assign _16_ = a[1];
  assign _20_ = b[1];
  assign _23_ = cin;
  assign _15_ = a[0];
  assign _19_ = b[0];
  assign _17_ = a[2];
  assign _21_ = b[2];
  assign sum[3] = _35_;
  assign sum[2] = _34_;
  assign sum[1] = _33_;
  assign sum[0] = _32_;
  assign cout = _24_;
  assign _18_ = a[3];
  assign _22_ = b[3];
endmodule
