/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "CLA/CLA_4bit.v:1.1-141.10" *)
module CLA_4bit_gate_level(a, b, cin, sum, cout);
  (* src = "CLA/CLA_4bit.v:2.18-2.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "CLA/CLA_4bit.v:3.18-3.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "CLA/CLA_4bit.v:4.18-4.21" *)
  input cin;
  wire cin;
  (* src = "CLA/CLA_4bit.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "CLA/CLA_4bit.v:6.18-6.22" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "CLA/CLA_4bit.v:14.22-14.24" *)
  wire c4;
  assign _00_ = ~(a[3] & b[3]);
  assign _01_ = a[3] ^ b[3];
  assign _10_ = ~(_03_ & _09_);
  assign _11_ = a[2] ^ b[2];
  assign _12_ = ~(_10_ & _11_);
  assign _13_ = ~(_02_ & _12_);
  assign _14_ = ~(_01_ & _13_);
  assign cout = ~(_00_ & _14_);
  assign sum[0] = cin ^ _05_;
  assign sum[1] = _07_ ^ _08_;
  assign sum[2] = _10_ ^ _11_;
  assign sum[3] = _01_ ^ _13_;
  assign _02_ = ~(a[2] & b[2]);
  assign _03_ = ~(a[1] & b[1]);
  assign _04_ = ~(a[0] & b[0]);
  assign _05_ = a[0] ^ b[0];
  assign _06_ = ~(cin & _05_);
  assign _07_ = ~(_04_ & _06_);
  assign _08_ = a[1] ^ b[1];
  assign _09_ = ~(_07_ & _08_);
  assign c4 = cout;
endmodule
