/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "RAC/RAC_1bit.v:1.1-16.10" *)
module FA_1bit(a, b, cin, sum, cout);
  (* src = "RAC/RAC_1bit.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "RAC/RAC_1bit.v:2.14-2.15" *)
  input b;
  wire b;
  (* src = "RAC/RAC_1bit.v:2.17-2.20" *)
  input cin;
  wire cin;
  (* src = "RAC/RAC_1bit.v:3.12-3.15" *)
  output sum;
  wire sum;
  (* src = "RAC/RAC_1bit.v:3.17-3.21" *)
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "RAC/RAC_1bit.v:2.11-2.12" *)
  wire _3_;
  (* src = "RAC/RAC_1bit.v:2.14-2.15" *)
  wire _4_;
  (* src = "RAC/RAC_1bit.v:2.17-2.20" *)
  wire _5_;
  (* src = "RAC/RAC_1bit.v:3.17-3.21" *)
  wire _6_;
  (* src = "RAC/RAC_1bit.v:3.12-3.15" *)
  wire _7_;
  sky130_fd_sc_hd__maj3_1 _8_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_6_)
  );
  sky130_fd_sc_hd__xor3_1 _9_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_7_)
  );
  assign cout = _6_;
  assign _5_ = cin;
  assign sum = _7_;
  assign _3_ = a;
  assign _4_ = b;
endmodule

(* top =  1  *)
(* src = "RAC/RAC_4bit.v:1.1-47.10" *)
module rac_4bit(a, b, cin, sum, cout);
  (* src = "RAC/RAC_4bit.v:2.18-2.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "RAC/RAC_4bit.v:3.18-3.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "RAC/RAC_4bit.v:4.18-4.21" *)
  input cin;
  wire cin;
  (* src = "RAC/RAC_4bit.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "RAC/RAC_4bit.v:6.18-6.22" *)
  output cout;
  wire cout;
  (* src = "RAC/RAC_4bit.v:9.10-9.12" *)
  wire c1;
  (* src = "RAC/RAC_4bit.v:9.14-9.16" *)
  wire c2;
  (* src = "RAC/RAC_4bit.v:9.18-9.20" *)
  wire c3;
  (* module_not_derived = 32'd1 *)
  (* src = "RAC/RAC_4bit.v:12.13-18.6" *)
  FA_1bit uut0 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RAC/RAC_4bit.v:21.13-27.6" *)
  FA_1bit uut1 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RAC/RAC_4bit.v:30.13-36.6" *)
  FA_1bit uut2 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RAC/RAC_4bit.v:39.13-45.6" *)
  FA_1bit uut3 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule
