/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "RAC/RAC_1bit.v:1.1-16.10" *)
module FA_1bit(a, b, cin, sum, cout);
  (* src = "RAC/RAC_1bit.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "RAC/RAC_1bit.v:2.14-2.15" *)
  input b;
  wire b;
  (* src = "RAC/RAC_1bit.v:2.17-2.20" *)
  input cin;
  wire cin;
  (* src = "RAC/RAC_1bit.v:3.12-3.15" *)
  output sum;
  wire sum;
  (* src = "RAC/RAC_1bit.v:3.17-3.21" *)
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  assign _0_ = ~(a & b);
  assign _1_ = a ^ b;
  assign _2_ = ~(cin & _1_);
  assign sum = cin ^ _1_;
  assign cout = ~(_0_ & _2_);
endmodule
