/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, GNU /usr/bin/c++ 15.2.0) */

(* src = "RAC/RAC_1bit.v:1.1-16.10" *)
module FA_1bit(a, b, cin, sum, cout);
  (* src = "RAC/RAC_1bit.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "RAC/RAC_1bit.v:2.14-2.15" *)
  input b;
  wire b;
  (* src = "RAC/RAC_1bit.v:2.17-2.20" *)
  input cin;
  wire cin;
  (* src = "RAC/RAC_1bit.v:3.12-3.15" *)
  output sum;
  wire sum;
  (* src = "RAC/RAC_1bit.v:3.17-3.21" *)
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "RAC/RAC_1bit.v:2.11-2.12" *)
  wire _3_;
  (* src = "RAC/RAC_1bit.v:2.14-2.15" *)
  wire _4_;
  (* src = "RAC/RAC_1bit.v:2.17-2.20" *)
  wire _5_;
  (* src = "RAC/RAC_1bit.v:3.17-3.21" *)
  wire _6_;
  (* src = "RAC/RAC_1bit.v:3.12-3.15" *)
  wire _7_;
  sky130_fd_sc_hd__maj3_1 _8_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_6_)
  );
  sky130_fd_sc_hd__xor3_1 _9_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_7_)
  );
  assign cout = _6_;
  assign _5_ = cin;
  assign sum = _7_;
  assign _3_ = a;
  assign _4_ = b;
endmodule
